### ISSUE TITLE
Standardizing Cronitor Clients

### ISSUE THREAD

**Issue by cronitorio** [cronitorio/cronitor-php#13]
Hi @nathanielks,

I hope you've been well! We'd like to start taking responsibility for providing Cronitor supported open-source client libraries. Our Github account would host the clients and take a more active roll in the development of all clients. We'd like to start with Ruby, Python, Java, PHP, Elixir, Javascript, and Bash - https://cronitor.io/docs/open-source-libraries - as well as open-source our own Go client.

Our goal is to help standardize documentation, nomenclature, feature development, and testing, as well as keeping the APIs current, and, in some cases, adding or consolidating Ping and Monitor APIs.

Ideally, we'd like to transfer ownership of existing libraries for continuity.  We'll clearly note original client authors on the README. And any maintainers who would like to continue contributing to the projects will continue to have maintainer access. Would you be interested in helping us do this for the PHP library?

**Comment by nathanielks** [comment]
Hi @cronitorio! I unfortunately haven't touched this for quite a long time and don't plan to do so in the future. I'm happy to transfer ownership, however!

**Comment by aflanagan** [comment]
Thanks! I just sent you an invite to our org. After you accept that you can transfer it over from the settings tab.

**Comment by nathanielks** [comment]
Transferred 😃

**Comment by aflanagan** [comment]
Thanks again!
