### ISSUE TITLE
Psr-4 autoload issue

### ISSUE THREAD

**Issue by ChargemapFranck** [cronitorio/cronitor-php#33]
Hello,

When I composer install with this library as a dependency I get the following warnings : 

```
Class Cronitor\ValidationException located in ./vendor/cronitor/cronitor-php/lib/Exception.php does not comply with psr-4 autoloading standard. Skipping.
Class Cronitor\ConfigurationException located in ./vendor/cronitor/cronitor-php/lib/Exception.php does not comply with psr-4 autoloading standard. Skipping.
```

This could be an issue for strict autoloaders
This can be fixed by splitting the two exceptions in two files that are correctly named.

**Comment by aflanagan** [comment]
@ChargemapFranck thanks! This has been merged and is available in the 1.1.1 release.
